name: Publish Docker image

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 5 * * 6" # Run at 5am daily

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: domwillcode/digitalocean-dyndns

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: domwillcode/digitalocean-dyndns:latest,${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

